### ISSUE TITLE
Jupiter notebook - 'TeleBot' object has no attribute 'message_handler'

### ISSUE THREAD

**Issue by NiklasC** [karipov/atlink#2]
Hey there,

I wanted to try out the at link code by basically copying into my Jupiter Notebook and modifying it from there. However on first try I get the following issue:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2b3ea344f58d> in <module>
      6 bot = telebot.TeleBot(bot_token)
      7 
----> 8 @bot.message_handler(commands=['start', 'help'])
      9 def send_welcome(message):
     10     bot.reply_to(message, "Test message - response")

AttributeError: 'TeleBot' object has no attribute 'message_handler'
```

This is the code I'm using:

```
import telebot
import time

bot_token = "My_generated_Token"
bot = telebot.TeleBot(bot_token)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Howdy, how are you doing?")

bot.polling()
```

Is there any way to resolve this problem?

**Comment by YoavRamon** [comment]
look in here: https://github.com/eternnoir/pyTelegramBotAPI/issues/278
try to use:
`pip uninstall telebot` then
`pip uninstall PyTelegramBotAPI` and then
`pip install PyTelegramBotAPI==2.2.3`

**Comment by karipov** [comment]
@NiklasC please report back on whether @YoavRamon's suggestion has fixed the issue for you.

**Comment by NiklasC** [comment]
I‘m sorry, I‘m not able to testing out until 6th of January. I’ll report back once I get back home from vacation

**Comment by karipov** [comment]
Seems like @YoavRamon’s answer fixes the issue. Closing.
